env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - http://host.docker.internal:3000
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: http://host.docker.internal:3000
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules:
  - action: WARN
    customMessage: ''
    id: 10015
  - action: WARN
    customMessage: ''
    id: 10017
  - action: WARN
    customMessage: ''
    id: 10020
  - action: WARN
    customMessage: ''
    id: 10021
  - action: FAIL
    customMessage: ''
    id: 10037
  - action: IGNORE
    customMessage: ''
    id: 10049
  - action: WARN
    customMessage: ''
    id: 10055
  - action: FAIL
    customMessage: ''
    id: 10063
  - action: IGNORE
    customMessage: ''
    id: 10094
  - action: IGNORE
    customMessage: ''
    id: 10096
  - action: IGNORE
    customMessage: ''
    id: 10109
  - action: WARN
    customMessage: ''
    id: 90003
  - action: WARN
    customMessage: ''
    id: 90004
  - action: IGNORE
    customMessage: ''
    id: 90005
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: zap-report-prod.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
